version: '3.7'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - ./backend:/usr/src/app
    env_file:
    - .env
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - 3000:3000
    networks:
      - things
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:latest
    command: 
      --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./dados:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Nx-74205
      MYSQL_DATABASE: things
      MYSQL_USER: things
      MYSQL_PASSWORD: Nx-74205
    networks:
      - things

networks:
  things:
    driver: bridge