// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuYvU7yasXm2N6DIS1SvkxhARG89alkEY',
    appId: '1:887045923890:web:e782150b665fa9c643482b',
    messagingSenderId: '887045923890',
    projectId: 'things-stuffs-1327e',
    authDomain: 'things-stuffs-1327e.firebaseapp.com',
    storageBucket: 'things-stuffs-1327e.appspot.com',
    measurementId: 'G-EYBVTE9PB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpdozZ4JhZsH-8iIY3VQvSqw50r2uQdQw',
    appId: '1:887045923890:android:b0be19b7ac5f797143482b',
    messagingSenderId: '887045923890',
    projectId: 'things-stuffs-1327e',
    storageBucket: 'things-stuffs-1327e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3mcI0ZpKCHX9PWi1BCkbfXKa1k7r23G8',
    appId: '1:887045923890:ios:4561f9f271283ae243482b',
    messagingSenderId: '887045923890',
    projectId: 'things-stuffs-1327e',
    storageBucket: 'things-stuffs-1327e.appspot.com',
    iosClientId: '887045923890-r4oag3bj3f3cabp521dsjdjj7f7kh1vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.thingsStuffs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3mcI0ZpKCHX9PWi1BCkbfXKa1k7r23G8',
    appId: '1:887045923890:ios:d3a625c0a35a39f943482b',
    messagingSenderId: '887045923890',
    projectId: 'things-stuffs-1327e',
    storageBucket: 'things-stuffs-1327e.appspot.com',
    iosClientId: '887045923890-5sldf7a6caado69713iebsq0a5qloa0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.thingsStuffs.RunnerTests',
  );
}
